### PR TITLE
Use debounce in timeslider instead of throttle

### PR DESCRIPTION
**Pull request by IncoCode**

### CODE REVIEW

**Comment by angieskazka** [comment]
it's conflicting most likely with mine b83e3460017259211e47d44bcbc1d991c2ec2025
can you please pull and resolve the conflict? 
feel free to override or remove my changes
@IncoCode

**Comment by IncoCode** [comment]
@angieskazka 
> it's conflicting most likely with mine b83e346

No :), debounce function was also added by me in another commit.

Done.

**Comment by angieskazka** [comment]
@IncoCode this has largely decreased performance. now the timeslider is fast but the picture is lagging a few seconds behind =/

**Comment by arthurcamara1** [comment]
Is "increases" performance by blocking repeated updates to the chart, basically. But we want to ensure some of them get triggered, that's why `throttling` seemed more natural

**Comment by arthurcamara1** [comment]
@IncoCode @angieskazka 

**Solution**
Decrease the interval in ms for debounce. That will maintain timeslider performant and increase the number of updates. The interval has a slight different meaning in `debounce` and `throttle`.

**Comment by arthurcamara1** [comment]
Try this (line 108 of components/timeslider/timeslider.js):

```javascript
this._setTime = utils.debounce(this._setTime, 2);
```

**Pull request merged**
