### PR TITLE
PA_57: Irrelevant entries are appeared in colors first dropdown

### PR DESCRIPTION
**Pull request by IncoCode**
#277

### CODE REVIEW

**Comment by angieskazka** [comment]
i doubt the solution is correct. It's a special case of a bigger issue #372. Requires not a quick fix, but a substantial changes of how we deal with metadata. Let's discuss it under #372

**Comment by IncoCode** [comment]
In this solution you can specify (in `gapminder.js`) which set of indicators should be in dropdown menu in different dialogs.

**Comment by angieskazka** [comment]
Still not convinced. The tools themselves should stay agnostic to which indicators they show. When a new indicator is added, it should appear or not appear in the list without editing gapminder.js. Having metadata stored in Gapminder.js solves the issue #277 but doesn't solve the underlying problem #372. 

@arthurcamara1 can you direct us on this?

**Comment by arthurcamara1** [comment]
Sure. I agree with @angieskazka.  We need to solve the whole issue #372. Hiding indicators or picking them from `gapminder.js` is a very very short term solution that is more of a hack. Ideally, `gapminder.js` should shrink to contain only build-specific features. Displaying indicators is not a specific feature, it just needs to be generic with meta data.

**Comment by angieskazka** [comment]
@IncoCode @arthurcamara1 see the updated description in #372

**Comment by angieskazka** [comment]
update: we are going to refactor some stuff and do it ourselves this week

**Pull request closed without merging**
