### PR TITLE
LC_31: Slider ball does not synchronized its position with lines of graph

### PR DESCRIPTION
**Pull request by IncoCode**
#244

### CODE REVIEW

**Comment by angieskazka** [comment]
the solution disables throttling. @IncoCode can you motivate it?

@arthurcamara1 please review

**Comment by IncoCode** [comment]
@angieskazka it is the reason why text doesn't synchronized with slider.

**Comment by IncoCode** [comment]
Actually we can disable throttling only for `brushEnd` function. Updated.

**Comment by angieskazka** [comment]
yes, this i can accept. Throttle on brush is absolutely needed because we don't want to call update events every 1ms

**Pull request merged**
