### PR TITLE
selected label shouldn't overlap with bubble

### PR DESCRIPTION
**Pull request by sergey-filipenko**

### CODE REVIEW

**Comment by arthurcamara1** [comment]
I checked the branch :+1: Thanks...

Can you update the PR?

I found the following problems:

- Not vertically centered when hovering the label. It needs to be centered in all screen profiles (small, medium and large screens)
screen shot 2015-09-25 at 4 22 05 pm

- Label is not within chart. When we drag the label outside the chart, it stays at this position:

screen shot 2015-09-25 at 4 22 14 pm

And it should be at this position:

screen shot 2015-09-25 at 4 22 20 pm

**Comment by sergey-filipenko** [comment]
@arthurcamara1 About hovering label: text align center for me. What browser are you use?

**Comment by angieskazka** [comment]
@sergey-filipenko  we mainly use Google Chrome on Mac and Windows. 
we also check that things work and look nice in Firefox on Mac and Windows, and in Safari on Mac
also in Google Chrome on Android and iOS devices

**Comment by arthurcamara1** [comment]
Aha! I saw you solved this though #550

screen shot 2015-09-25 at 8 11 41 pm

Great! Awesome. I think if you just center the work vertically we can merge.
And then we solve the other issue #552 :)

**Comment by arthurcamara1** [comment]
:smile: :open_mouth: AAAAALMOST THERE

In the current version, if we select a bubble, let's say Colombia, and then drag the timeslider from 1800 to 2015, with the trails option selected, the label stays pointing to the first bubble. In case the bubble is not in the visible area, the label still is:

screen shot 2015-09-29 at 4 00 31 pm

And this behavior is correct.

However, in this Pull Request, this feature is disabled, so it disappears when the first trail is not visible:

image

The label should be visible at all times. :)

**Comment by arthurcamara1** [comment]
Also, see how the text label is vertically centralized in the current version:

screen shot 2015-09-29 at 4 09 37 pm

And in your version (no padding at the top of the label):

screen shot 2015-09-29 at 4 10 00 pm

**Comment by arthurcamara1** [comment]
Awesome. It now works here.

There are two little problems:

1. The vertical center
2. The close button is cropped then the label is at the very top

screen shot 2015-09-29 at 6 19 40 pm

But since those are just two little visual glitches and easy to fix, I'll merge this PR.

**Pull request merged**
