### PR TITLE
Hide pop-up on clicking outside

### PR DESCRIPTION
**Pull request by TBAPI-0KA**

### CODE REVIEW

**Comment by angieskazka** [comment]
@arthurcamara1 is it ok to use d3.select("body") within buttonlist?
or is it better to listen on a tool element level, and call closeDialogs of its component?

**Comment by arthurcamara1** [comment]
@TBAPI-0KA 

Like @angieskazka suggested, we should not bind it to body. Vizabi is an embeddable tool (and we want to "pollute" the external page as little as possible), so the rule of thumb so far is that we try to avoid anything outside the tool element.

**How to do it:**
There's a reference to the root at every component (the root is the tool), and you can access the root's element:

```javascript
this.root.element //will return the DOM element associated with the root
```

So, on line 188 of your file `buttonlist/buttonlist.js`, just select the root element with d3:

```javascript
d3.select(this.root.element).on("mousedown", function (e) { ... });
```

That will capture the click within Vizabi's scope only.

**Comment by angieskazka** [comment]
yes. btw, i know i once made a `ctrl` key listener myself which was bound to "body". it's still in bubble chart L386, and it's not something you should take for a role model.

actually, i don't know how to listen to meta keys on anything other than "body" or "window". it's different from catching a click, because click happens on element and key press happens generic

suggestions welcomed @arthurcamara1 @TBAPI-0KA

**Comment by arthurcamara1** [comment]
@angieskazka in that case you will have to bind it to body or window. It would probably be good practice in that case, though, to check if `body` is available, and use a `root` variable:

Something like:

```js
//bubble chart file

(function () {
  "use strict";
  var root = this;
  var Vizabi = root.Vizabi;

  ...

  //now I want to bind to body

  if(root.document && root.document.body) {
      //bind here
  }

  ...

}).call(this);
```

**Comment by arthurcamara1** [comment]
I’ll merge this and fix that one line, since it’s so simple and poses no break

line 188 of your file `buttonlist/buttonlist.js`, that is

**Pull request merged**
